### ISSUE TITLE
Add a configuration file to tweak the editor's settings

### ISSUE THREAD

**Issue by avdb13** [x1unix/go-playground#146]
One should be able to set things like the font and dark mode globally. This is because my browser doesn't save cookies or site settings causing me to change this every time I visit my playground.

**Comment by x1unix** [comment]
@avdb13 editor settings are stored in local storage and dont use cookies.

I need a feedback/vote from other users because this is very specific problem and probably don't affect a major percentage of users.

I plan to add automatic dark mode detection using `prefers-color-scheme` instead of manual toggle.

What browser do you use? Its a very exotic case.

**Comment by x1unix** [comment]
@avdb13 I see. Looks like it also breaks `localStorage`.

>  A "cookie" block permission also controls localStorage/sessionStorage, indexedDB,
    * sharedWorkers and serviceWorkers

I have some good news to you - in recent release I added system theme support. Playground dark theme is synchronized with browser/OS settings.

Just clean browser cache to ensure that you're using the latest version of website.

**Comment by x1unix** [comment]
@avdb13 btw I don't believe that such configs really helps to protect against tracking.

* JavaScript is still enabled (although nowadays almost any site relies on it)
* It doesn't prevent from tracking using `ETag` header.
