### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by cichy** [x1unix/go-playground#183]
Does it require linux os for local dev?
Mac Big Sur
ver. 11.6.6
Intel-dual core i5
ERROR: This installation script doesn't support Darwin. Only Linux systems are supported.
make: *** [install] Error 4

**Comment by x1unix** [comment]
@cichy installation script only supports Linux because it used to install the playground as Systemd service.

Use `make build` to build the app without installation.

If you want to start the app in development mode, use these commands:

* `make build-webworker` to build a WebAssembly worker that checks Go syntax
* `make run` - to start the API server
* `make ui` - to start React frontend dev server (webpack)

Also, please run `yarn --cwd=web install` to install npm dependencies for frontend.
