### ISSUE TITLE
Test files cannot be played

### ISSUE THREAD

**Issue by maxatome** [x1unix/go-playground#324]
Hi,

Using https://staging.goplay.tools/

Choose any test example (New Empty Test for example) then click Run
```
play: no non-test Go files in /tmp/sandbox1983726817
```

Thanks for your work!

**Comment by x1unix** [comment]
@maxatome issue is caused by a bug in original Go Playground API - https://github.com/golang/go/issues/68327

Better Go Playground always explicitly send all file names to API, like this:

```
-- some_test.go --
package main

...
```

Looks like, their unit test detector doesn't like that. I will add workaround for that, but tests won't work if you have multiple files.
