### ISSUE TITLE
Option to revert back a few "enhancements" + more

### ISSUE THREAD

**Issue by MarkMoretto** [x1unix/go-playground#400]
**Is your feature request related to a problem? Please describe.**
I love using goplay.tools for on-the-fly Go validation and recommended it to most everyone who used Go over the go.dev playground.  However, recent iterations of the platform have make it overly complicated or silly to use.

Notable gripes and suggestions:  

* Upload a file: Why?  People cannot copy-and-paste their code?
* Local storage: I think whatever we worked on last time reappears when we go back to goplay.tools vs. having a clean canvas.  I try to not have any browser restrictions (eg - uBlock, Tracking Blockers) on the website because it is useful and if you can make a few bucks from user data to keep it running, then that's great. But, will have to enable those if it means less local storage and a new canvas with each subsequent visit to the website.
* Font: We can increase the terminal font size, but not the editor font size, correct?  I would think the opposite would be ideal.
* Suggestions: Seem too quick. It would be great to add some lag to these.
* Errors: Nothing is really highlighted for errors, which keeps in line with a lightweight platform for porottyping, but I'd rather see error highlighting vs. file uploading.

**Describe the solution you'd like**
Stop "enhancing" things.  Or, provide an option for a lightweight version of the tool.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by x1unix** [comment]
You actually can increase editor font side in the same way as in VSCode - by holding Ctrl/Meta and mouse wheel scroll

**Comment by x1unix** [comment]
> Upload a file: Why? People cannot copy-and-paste their code?

They can, this is just a convenience option since the first option. Also copy-pasting code on mobile devices might be problematic without app to edit code.

> Local storage: I think whatever we worked on last time reappears when we go back to goplay.tools vs. having a clean canvas

Auto-save will be an optional feature in next version, but local storage can't be fully removed as it used to persist settings.

> Suggestions: Seem too quick. It would be great to add some lag to these.

I can't control that as [monaco editor](https://microsoft.github.io/monaco-editor/) library responsible for that.

> Errors: Nothing is really highlighted for errors

What are you talking about? Simple syntax errors are highlighted. 
![image](https://github.com/user-attachments/assets/726badd9-3423-4037-bbcc-f26adb235c30)

Any more advanced errors (type check, imports, etc) will require integration of a full LSP server but as you said yourself, it's better to keep playground "a lightweight platform for prototyping".
